### ISSUE TITLE
choke specifics

### ISSUE THREAD

**Issue by vxq9e7bx** [mhier/LauraBox#2]
Hi Martin,
can you please point me to the choke you have built into your setup? Making modifications to the pcb layout is beyond my capabilities, and I would gladly build my own copy of your LauraBox :)

Thanks in advance :)

**Comment by mhier** [comment]
I am sorry, I totally overlooked your question... It was this one: https://www.mouser.de/ProductDetail/710-7448640415

I am sure you can replace it by any other big enough choke. The one I picked is surely over-dimensioned. I have no expertise to pick it properly...
